/**
 * Pin theme from reference image (prompt-image-to-pin-theme-js.txt).
 * Fonts/style match reference: Montserrat Black (title), Dancing Script (accent), Arial (URL), band #1a434e.
 * Insert: python scripts/insert_pin_templates.py --from-js pin_templates/themes_from_ai/pin_theme_listicle_50.js
 */
module.exports = {
  THEMES: [
    {
      template_id: "listicle_50",
      template_name: "listicle_50",
      style_slots: {
        band: { background_color: "primary" },
        badge_circle: { background: "white", border: "accent" },
        accent_text: { color: "on_primary" },
        title: { color: "on_primary" },
        footer_pill: { background_color: "on_light" },
        website: { color: "on_light" },
      },
      font_slots: {
        badge_number: "body",
        accent_text: "accent",
        title: "heading",
        website: "body",
      },
      template_data: {
        name: "50 Listicle Pin",
        canvas: { width: 736, height: 1308, aspect_ratio: "9:16" },
        prompt: "Generate text for each field based on the recipe title. Return a JSON object only.",
        field_prompts: {
          badge_number: "Generate a number or short count for recipe list (e.g. 50, 30, 10). Output only the number or 2-3 words.",
          accent_text: "Generate a 2-word catchy phrase for recipe {{title}}, e.g. Super Simple, So Easy.",
          title: "Generate a short all-caps recipe category title for {{title}}, 2-4 words.",
        },
        images: {
          top_image: {
            position: { top: 0, left: 0 },
            width: 736,
            height: 523,
            layer_order: 1,
          },
          bottom_left: {
            position: { top: 850, left: 0 },
            width: 368,
            height: 458,
            layer_order: 2,
          },
          bottom_right: {
            position: { top: 850, left: 368 },
            width: 368,
            height: 458,
            layer_order: 2,
          },
        },
        elements: {
          band: {
            type: "div",
            position: { top: 490, left: -30 },
            width: 796,
            height: 300,
            background_color: "#1a434e",
            rotation: -2,
            z_index: 5,
          },
          badge_circle: {
            type: "div",
            position: { top: 455, left: 48 },
            width: 80,
            height: 80,
            background_color: "#ffffff",
            border: { width: 2, style: "dotted", color: "#000000" },
            border_radius: 40,
            z_index: 10,
          },
          badge_number: {
            type: "text",
            text: "50",
            position: { top: 478, left: 48 },
            width: 80,
            height: 44,
            font_family: "Montserrat Black, Arial Black, sans-serif",
            font_size: 34,
            font_weight: "900",
            color: "#000000",
            text_align: "center",
            z_index: 11,
          },
          accent_text: {
            type: "text",
            text: "Super Simple",
            position: { top: 532, left: 145 },
            width: 260,
            height: 40,
            font_family: "Dancing Script, Great Vibes, cursive",
            font_size: 28,
            font_weight: "normal",
            color: "#ffffff",
            text_align: "left",
            rotation: 1,
            z_index: 12,
          },
          title: {
            type: "text",
            text: "Recipe Category Title",
            position: { top: 568, left: 145 },
            width: 460,
            height: 72,
            font_family: "Montserrat Black, Futura, Arial Black, sans-serif",
            font_size: 38,
            font_weight: "900",
            color: "#ffffff",
            text_align: "left",
            line_height: 1.08,
            rotation: -2,
            z_index: 12,
          },
          footer_pill: {
            type: "div",
            position: { top: 1254, left: 218 },
            width: 300,
            height: 44,
            background_color: "#ffffff",
            border_radius: 22,
            z_index: 15,
          },
          website: {
            type: "text",
            text: "{{domain}}",
            position: { top: 1256, left: 218 },
            width: 300,
            height: 40,
            font_family: "Arial, Helvetica, sans-serif",
            font_size: 14,
            font_weight: "300",
            color: "#000000",
            text_align: "center",
            z_index: 20,
          },
        },
      },
    },
  ],
};
